/** A real plan computed by the API for the seeded Crestline Markets order — sample data for the landing page. */
import type { LoadPlan } from '../../api/types';

export const SAMPLE_PLAN: LoadPlan = {
  order_id: 1,
  company_name: 'Crestline Markets',
  floor_pattern: 'straight',
  sequence: 'heaviest_to_nose',
  max_height: 2,
  heavy_bottom: true,
  slip_sheets: true,
  label_direction: 'facing_out',
  segregate_categories: false,
  max_pallets: null,
  special: 'Double-wrap all pallets. No product overhang beyond pallet edge.',
  rows: 13,
  floor_positions: 26,
  stacks_used: 5,
  total_pallets: 10,
  total_weight_lbs: 10600.0,
  checklist: [
    'Max 2 pallets high',
    'Straight load: 48" side along the trailer',
    'Heaviest pallets to the nose',
    'Heavy on the bottom, light on top',
    'Slip sheet between every layer',
    'Labels facing out',
  ],
  warnings: [],
  pallets: [
    {
      load_sequence: 1,
      row: 0,
      side: 'left',
      level: 0,
      orientation: 'lengthwise',
      sku: 'CRM-RF-1002',
      product_name: 'Crestline Whole Milk 1 Gal',
      category: 'Refrigerated',
      cases: 36,
      weight_lbs: 1274.0,
      partial: false,
      stop: 2,
    },
    {
      load_sequence: 2,
      row: 0,
      side: 'left',
      level: 1,
      orientation: 'lengthwise',
      sku: 'CRM-FZ-1001',
      product_name: 'Crestline Frozen Chicken Breasts',
      category: 'Frozen',
      cases: 48,
      weight_lbs: 1250.0,
      partial: false,
      stop: 1,
    },
    {
      load_sequence: 3,
      row: 0,
      side: 'right',
      level: 0,
      orientation: 'lengthwise',
      sku: 'CRM-RF-1002',
      product_name: 'Crestline Whole Milk 1 Gal',
      category: 'Refrigerated',
      cases: 36,
      weight_lbs: 1274.0,
      partial: false,
      stop: 2,
    },
    {
      load_sequence: 4,
      row: 0,
      side: 'right',
      level: 1,
      orientation: 'lengthwise',
      sku: 'CRM-FZ-1001',
      product_name: 'Crestline Frozen Chicken Breasts',
      category: 'Frozen',
      cases: 48,
      weight_lbs: 1250.0,
      partial: false,
      stop: 1,
    },
    {
      load_sequence: 5,
      row: 1,
      side: 'left',
      level: 0,
      orientation: 'lengthwise',
      sku: 'CRM-RF-1002',
      product_name: 'Crestline Whole Milk 1 Gal',
      category: 'Refrigerated',
      cases: 36,
      weight_lbs: 1274.0,
      partial: false,
      stop: 2,
    },
    {
      load_sequence: 6,
      row: 1,
      side: 'left',
      level: 1,
      orientation: 'lengthwise',
      sku: 'CRM-FZ-1001',
      product_name: 'Crestline Frozen Chicken Breasts',
      category: 'Frozen',
      cases: 48,
      weight_lbs: 1250.0,
      partial: false,
      stop: 1,
    },
    {
      load_sequence: 7,
      row: 1,
      side: 'right',
      level: 0,
      orientation: 'lengthwise',
      sku: 'CRM-RF-1002',
      product_name: 'Crestline Whole Milk 1 Gal',
      category: 'Refrigerated',
      cases: 36,
      weight_lbs: 1274.0,
      partial: false,
      stop: 2,
    },
    {
      load_sequence: 8,
      row: 1,
      side: 'right',
      level: 1,
      orientation: 'lengthwise',
      sku: 'CRM-RF-1002',
      product_name: 'Crestline Whole Milk 1 Gal',
      category: 'Refrigerated',
      cases: 6,
      weight_lbs: 254.0,
      partial: true,
      stop: 2,
    },
    {
      load_sequence: 9,
      row: 2,
      side: 'left',
      level: 0,
      orientation: 'lengthwise',
      sku: 'CRM-FZ-1001',
      product_name: 'Crestline Frozen Chicken Breasts',
      category: 'Frozen',
      cases: 48,
      weight_lbs: 1250.0,
      partial: false,
      stop: 1,
    },
    {
      load_sequence: 10,
      row: 2,
      side: 'left',
      level: 1,
      orientation: 'lengthwise',
      sku: 'CRM-FZ-1001',
      product_name: 'Crestline Frozen Chicken Breasts',
      category: 'Frozen',
      cases: 8,
      weight_lbs: 250.0,
      partial: true,
      stop: 1,
    },
  ],
};
